### ISSUE TITLE
Error: ActionUpdateThread.OLD_EDT` is deprecated and going to be  removed soon

### ISSUE THREAD

**Issue by toby1984** [xusoo/duplicate-lines-intellij-plugin#5]
Hi,

Seems the plugin needs to be updated ; IntelliJ 2024.2.0.2 shows the following error:

    2024-08-22 14:59:00,652 [ 964886] SEVERE - #DuplicateLines - `ActionUpdateThread.OLD_EDT` is deprecated and going to be   removed soon. 'DuplicateLines' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread   javadoc. [Plugin: DuplicateLines]
    com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon.   'DuplicateLines' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin:   DuplicateLines]
   	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by jonnypowell** [comment]
Seems @toby1984 just beat me to it! I'm seeing the same error each time I use it in IJ 2024.2.0.2, MacOS, MBP M1

**Comment by toby1984** [comment]
> Seems @toby1984 just beat me to it! I'm seeing the same error each time I use it in IJ 2024.2.0.2, MacOS, MBP M1

Though I have to admit I just found out that IntelliJ also has  "Edit->Duplicate Line" feature  (not sure that was the case many years ago when I installed this plugin) so I just uninstalled the plugin and am now using the built-in feature.

**Comment by jonnypowell** [comment]
Having come from Eclipse many, many years ago, it's the ability to duplicate both up & down that I still find convenient. As far as I know, the built-in function only duplicates down.

**Comment by HaLo1701** [comment]
Correct, the build-in function only duplicates down.
I am coming from NetBeans and there you can duplicate in both directions too and it is very useful.

**Comment by grgrzybek** [comment]
#6 works for me, but I don't know how to proceed from there (publish to IDEA marketplace)...
Is there a chance @xusoo you publish fixed version?

**Comment by toby1984** [comment]
@xusoo Any chance you could publish the fix by @grgrzybek ?

**Comment by xusoo** [comment]
New 1.1.0 version is now available fixing this error message. Thanks @grgrzybek for the PR!

https://plugins.jetbrains.com/plugin/10008-duplicate-lines
